# Twitter API credentials v1
API_KEY = 'API_KEY'
API_SECRET = 'API_SECRET'
ACCESS_TOKEN = 'ACCESS_TOKEN'
ACCESS_TOKEN_SECRET = 'ACCESS_TOKEN_SECRET'
# Client secret 2.0
CLIENT_SECRET = 'CLIENT_SECRET'
BEARER_TOKEN = "BEARER_TOKEN"
